### PR TITLE
style: standardize greys

### PR DESCRIPTION
**Pull request by cabreraalex**

### CODE REVIEW

**Comment by Sparkier** [comment]
+ to me some of the differences are too subtle now and text too close to normal text even when not in highlight state (e.g. dismiss, model options, ...)

**Comment by Sparkier** [comment]
maybe we should have something like:
```
gray-inactive: '#...'
gray-active: '#...'
gray-hovered: '#...'
```

**Comment by Sparkier** [comment]
Did that in this commit: 9aebcabb6df3ef196b16df9dfe923c93e9339fc6
Let me know what you think.

**Comment by cabreraalex** [comment]
fantastic idea!!!

**Comment by cabreraalex** [comment]
you have to approve but this looks awesome, go ahead and merge

**Review by Sparkier — APPROVED** [review]

**Pull request merged**
